type :: qes_types_module_type
  logical :: is_alloc = .false.
  logical :: is_init = .false.
  type :: closed_type
  character(len=100) :: tagname
  logical :: lread = .true.
  logical :: lwrite = .true.
  character(len=256) :: DATE
  character(len=256) :: TIME
  character(len=256) :: closed
  type :: status_type
  integer :: status
  type :: scalarQuantity_type
  character(len=256) :: Units
  real(dp) :: scalarQuantity
  type :: finiteFieldOut_type
  real(dp), dimension(3) :: electronicDipole
  real(dp), dimension(3) :: ionicDipole
  type :: k_point_type
  logical :: weight_ispresent
  real(dp) :: weight
  logical :: label_ispresent
  character(len=256) :: label
  type(k_point_type), allocatable, dimension(:) :: k_point
  type :: atom_type
  character(len=256) :: name
  logical :: position_ispresent
  character(len=256) :: position
  logical :: index_ispresent
  integer :: index
  type(atom_type), allocatable, dimension(:) :: atom
  type :: phase_type
  logical :: ionic_ispresent
  real(dp) :: ionic
  logical :: electronic_ispresent
  real(dp) :: electronic
  logical :: modulus_ispresent
  real(dp) :: modulus
  type(phase_type) :: phase
  type :: dipoleOutput_type
  integer :: idir
  type(scalarquantity_type) :: dipole
  type(scalarquantity_type) :: ion_dipole
  type(scalarquantity_type) :: elec_dipole
  type(scalarquantity_type) :: dipoleField
  type(scalarquantity_type) :: potentialAmp
  type(scalarquantity_type) :: totalLength
  type :: polarization_type
  type(polarization_type) :: polarization
  real(dp), dimension(3) :: direction
  type :: ionicPolarization_type
  type(atom_type) :: ion
  real(dp) :: charge
  type :: electronicPolarization_type
  type(k_point_type) :: firstKeyPoint
  logical :: spin_ispresent
  type(spin_type) :: spin
  type :: BerryPhaseOutput_type
  type(phase_type) :: totalPhase
  type(ionicpolarization_type), allocatable, dimension(:) :: ionicPolarization
  type(electronicpolarization_type), allocatable, dimension(:) :: electronicPolarization
  integer :: ndim_ionicPolarization
  integer :: ndim_electronicPolarization
  type :: vector_type
  integer :: ndim_vec
  real(dp), allocatable, dimension(:) :: vec
  type :: ks_energies_type
  integer :: npw
  integer :: ndim_eigenvalues
  real(dp), allocatable, dimension(:) :: eigenvalues
  integer :: ndim_occupations
  type(occupations_type) :: occupations
  type :: magnetization_type
  logical :: lsda
  logical :: noncolin
  logical :: spinorbit
  real(dp) :: total
  real(dp) :: absolute
  logical :: do_magnetization
  type :: reciprocal_lattice_type
  real(dp), dimension(3) :: b1
  real(dp), dimension(3) :: b2
  real(dp), dimension(3) :: b3
  type :: basisSetItem_type
  integer :: nr1
  integer :: nr2
  integer :: nr3
  character(len=256) :: basisSetItem
  type :: equivalent_atoms_type
  integer :: nat
  integer :: ndim_index_list
  integer, allocatable, dimension(:) :: index_list
  type :: info_type
  logical :: name_ispresent
  logical :: class_ispresent
  character(len=256) :: class
  logical :: time_reversal_ispresent
  logical :: time_reversal
  type(info_type) :: info
  type :: matrix_type
  integer :: ndim1_mat
  integer :: ndim2_mat
  real(dp), allocatable, dimension(:,:) :: mat
  type :: symmetry_type
  type(matrix_type) :: rotation
  logical :: fractional_translation_ispresent
  real(dp), dimension(3) :: fractional_translation
  logical :: equivalent_atoms_ispresent
  type(equivalent_atoms_type) :: equivalent_atoms
  type :: algorithmic_info_type
  logical :: real_space_q
  logical :: uspp
  logical :: paw
  type :: opt_conv_type
  integer :: n_opt_steps
  real(dp) :: grad_norm
  type :: scf_conv_type
  integer :: n_scf_steps
  real(dp) :: scf_error
  type :: species_type
  logical :: mass_ispresent
  real(dp) :: mass
  character(len=256) :: pseudo_file
  logical :: starting_magnetization_ispresent
  real(dp) :: starting_magnetization
  logical :: spin_teta_ispresent
  real(dp) :: spin_teta
  logical :: spin_phi_ispresent
  real(dp) :: spin_phi
  type :: total_energy_type
  real(dp) :: etot
  logical :: eband_ispresent
  real(dp) :: eband
  logical :: ehart_ispresent
  real(dp) :: ehart
  logical :: vtxc_ispresent
  real(dp) :: vtxc
  logical :: etxc_ispresent
  real(dp) :: etxc
  logical :: ewald_ispresent
  real(dp) :: ewald
  logical :: demet_ispresent
  real(dp) :: demet
  logical :: efieldcorr_ispresent
  real(dp) :: efieldcorr
  logical :: potentiostat_contr_ispresent
  real(dp) :: potentiostat_contr
  type :: convergence_info_type
  type(scf_conv_type) :: scf_conv
  logical :: opt_conv_ispresent
  type(opt_conv_type) :: opt_conv
  type :: outputElectricField_type
  logical :: BerryPhase_ispresent
  type(berryphaseoutput_type) :: BerryPhase
  logical :: finiteElectricFieldInfo_ispresent
  type(finitefieldout_type) :: finiteElectricFieldInfo
  logical :: dipoleInfo_ispresent
  type(dipoleoutput_type) :: dipoleInfo
  type :: spin_constraints_type
  type(spin_constraints_type) :: spin_constraints
  real(dp) :: lagrange_multiplier
  logical :: target_magnetization_ispresent
  real(dp), dimension(3) :: target_magnetization
  type :: constr_type_type
  type :: constr_parms_list_type
  type :: atomic_constraint_type
  real(dp), dimension(4) :: constr_parms
  character(len=256) :: constr_type
  real(dp) :: constr_target
  type :: atomic_constraints_type
  integer :: num_of_constraints
  real(dp) :: tolerance
  type(atomic_constraint_type), allocatable, dimension(:) :: atomic_constraint
  integer :: ndim_atomic_constraint
  type :: electric_potential_type
  type :: electric_field_type
  character(len=256) :: electric_potential
  logical :: dipole_correction_ispresent
  logical :: dipole_correction
  logical :: electric_field_direction_ispresent
  integer :: electric_field_direction
  logical :: potential_max_position_ispresent
  real(dp) :: potential_max_position
  logical :: potential_decrease_width_ispresent
  real(dp) :: potential_decrease_width
  logical :: electric_field_amplitude_ispresent
  real(dp) :: electric_field_amplitude
  logical :: electric_field_vector_ispresent
  real(dp), dimension(3) :: electric_field_vector
  logical :: nk_per_string_ispresent
  integer :: nk_per_string
  logical :: n_berry_cycles_ispresent
  integer :: n_berry_cycles
  type :: symmetries_type
  integer :: nsym
  integer :: nrot
  integer :: space_group
  type(symmetry_type), allocatable, dimension(:) :: symmetry
  integer :: ndim_symmetry
  type :: ekin_functional_type
  real(dp) :: ecfixed
  real(dp) :: qcutz
  real(dp) :: q2sigma
  type :: esm_type
  character(len=256) :: bc
  integer :: nfit
  real(dp) :: w
  real(dp) :: efield
  type :: boundary_conditions_type
  character(len=256) :: assume_isolated
  logical :: esm_ispresent
  type(esm_type) :: esm
  logical :: fcp_opt_ispresent
  logical :: fcp_opt
  logical :: fcp_mu_ispresent
  real(dp) :: fcp_mu
  type :: symmetry_flags_type
  logical :: nosym
  logical :: nosym_evc
  logical :: noinv
  logical :: no_t_rev
  logical :: force_symmorphic
  logical :: use_all_frac
  type :: integerMatrix_type
  integer :: ndim1_int_mat
  integer :: ndim2_int_mat
  integer, allocatable, dimension(:,:) :: int_mat
  type :: cell_control_type
  character(len=256) :: cell_dynamics
  real(dp) :: pressure
  logical :: wmass_ispresent
  real(dp) :: wmass
  logical :: cell_factor_ispresent
  real(dp) :: cell_factor
  logical :: fix_volume_ispresent
  logical :: fix_volume
  logical :: fix_area_ispresent
  logical :: fix_area
  logical :: isotropic_ispresent
  logical :: isotropic
  logical :: free_cell_ispresent
  type(integermatrix_type) :: free_cell
  type :: md_type
  character(len=256) :: pot_extrapolation
  character(len=256) :: wfc_extrapolation
  character(len=256) :: ion_temperature
  real(dp) :: timestep
  real(dp) :: tempw
  real(dp) :: tolp
  real(dp) :: deltaT
  integer :: nraise
  type :: bfgs_type
  integer :: ndim
  real(dp) :: trust_radius_min
  real(dp) :: trust_radius_max
  real(dp) :: trust_radius_init
  real(dp) :: w1
  real(dp) :: w2
  type :: ion_control_type
  character(len=256) :: ion_dynamics
  logical :: upscale_ispresent
  real(dp) :: upscale
  logical :: remove_rigid_rot_ispresent
  logical :: remove_rigid_rot
  logical :: refold_pos_ispresent
  logical :: refold_pos
  logical :: bfgs_ispresent
  type(bfgs_type) :: bfgs
  logical :: md_ispresent
  type(md_type) :: md
  type :: monkhorst_pack_type
  integer :: nk1
  integer :: nk2
  integer :: nk3
  integer :: k1
  integer :: k2
  integer :: k3
  type(monkhorst_pack_type) :: monkhorst_pack
  type :: k_points_IBZ_type
  logical :: monkhorst_pack_ispresent
  logical :: nk_ispresent
  integer :: nk
  logical :: k_point_ispresent
  integer :: ndim_k_point
  type :: occupations_type
  type :: mixingMode_type
  type :: diago_type
  type :: electron_control_type
  character(len=256) :: diagonalization
  character(len=256) :: mixing_mode
  real(dp) :: mixing_beta
  real(dp) :: conv_thr
  integer :: mixing_ndim
  integer :: max_nstep
  logical :: tq_smoothing
  logical :: tbeta_smoothing
  real(dp) :: diago_thr_init
  logical :: diago_full_acc
  integer :: diago_cg_maxiter
  type :: basis_set_type
  logical :: gamma_only_ispresent
  logical :: gamma_only
  real(dp) :: ecutwfc
  logical :: ecutrho_ispresent
  real(dp) :: ecutrho
  type(basissetitem_type) :: fft_grid
  logical :: fft_smooth_ispresent
  type(basissetitem_type) :: fft_smooth
  logical :: fft_box_ispresent
  type(basissetitem_type) :: fft_box
  integer :: ngm
  logical :: ngms_ispresent
  integer :: ngms
  integer :: npwx
  type(reciprocal_lattice_type) :: reciprocal_lattice
  type :: basis_type
  logical :: fft_grid_ispresent
  type :: inputOccupations_type
  integer :: ispin
  real(dp) :: spin_factor
  type :: smearing_type
  real(dp) :: degauss
  type(smearing_type) :: smearing
  type :: band_structure_type
  integer :: nbnd
  logical :: nbnd_up_ispresent
  integer :: nbnd_up
  logical :: nbnd_dw_ispresent
  integer :: nbnd_dw
  real(dp) :: nelec
  logical :: num_of_atomic_wfc_ispresent
  integer :: num_of_atomic_wfc
  logical :: wf_collected
  logical :: fermi_energy_ispresent
  real(dp) :: fermi_energy
  logical :: highestOccupiedLevel_ispresent
  real(dp) :: highestOccupiedLevel
  logical :: two_fermi_energies_ispresent
  integer :: ndim_two_fermi_energies
  real(dp), allocatable, dimension(:) :: two_fermi_energies
  type(k_points_ibz_type) :: starting_k_points
  integer :: nks
  type(occupations_type) :: occupations_kind
  logical :: smearing_ispresent
  type(ks_energies_type), allocatable, dimension(:) :: ks_energies
  integer :: ndim_ks_energies
  type :: bands_type
  logical :: nbnd_ispresent
  logical :: tot_charge_ispresent
  real(dp) :: tot_charge
  logical :: tot_magnetization_ispresent
  real(dp) :: tot_magnetization
  logical :: inputOccupations_ispresent
  type(inputoccupations_type), allocatable, dimension(:) :: inputOccupations
  integer :: ndim_inputOccupations
  type :: spin_type
  type :: HubbardCommon_type
  character(len=256) :: specie
  real(dp) :: HubbardCommon
  type :: HubbardProj_type
  type :: Hubbard_ns_type
  type :: starting_ns_type
  type :: HubbardJ_type
  real(dp), dimension(3) :: HubbardJ
  type :: vdW_type
  character(len=256) :: vdw_corr
  logical :: non_local_term_ispresent
  character(len=256) :: non_local_term
  logical :: london_s6_ispresent
  real(dp) :: london_s6
  logical :: ts_vdw_econv_thr_ispresent
  real(dp) :: ts_vdw_econv_thr
  logical :: ts_vdw_isolated_ispresent
  logical :: ts_vdw_isolated
  logical :: london_rcut_ispresent
  real(dp) :: london_rcut
  logical :: xdm_a1_ispresent
  real(dp) :: xdm_a1
  logical :: xdm_a2_ispresent
  real(dp) :: xdm_a2
  logical :: london_c6_ispresent
  type(hubbardcommon_type), allocatable, dimension(:) :: london_c6
  integer :: ndim_london_c6
  type :: dftU_type
  logical :: lda_plus_u_kind_ispresent
  integer :: lda_plus_u_kind
  logical :: Hubbard_U_ispresent
  type(hubbardcommon_type), allocatable, dimension(:) :: Hubbard_U
  logical :: Hubbard_J0_ispresent
  type(hubbardcommon_type), allocatable, dimension(:) :: Hubbard_J0
  logical :: Hubbard_alpha_ispresent
  type(hubbardcommon_type), allocatable, dimension(:) :: Hubbard_alpha
  logical :: Hubbard_beta_ispresent
  type(hubbardcommon_type), allocatable, dimension(:) :: Hubbard_beta
  logical :: Hubbard_J_ispresent
  type(hubbardj_type), allocatable, dimension(:) :: Hubbard_J
  logical :: starting_ns_ispresent
  type(starting_ns_type), allocatable, dimension(:) :: starting_ns
  logical :: Hubbard_ns_ispresent
  type(hubbard_ns_type), allocatable, dimension(:) :: Hubbard_ns
  logical :: U_projection_type_ispresent
  character(len=256) :: U_projection_type
  integer :: ndim_Hubbard_U
  integer :: ndim_Hubbard_J0
  integer :: ndim_Hubbard_alpha
  integer :: ndim_Hubbard_beta
  integer :: ndim_Hubbard_J
  integer :: ndim_starting_ns
  integer :: ndim_Hubbard_ns
  type :: qpoint_grid_type
  integer :: nqx1
  integer :: nqx2
  integer :: nqx3
  type(qpoint_grid_type) :: qpoint_grid
  type :: hybrid_type
  real(dp) :: ecutfock
  real(dp) :: exx_fraction
  real(dp) :: screening_parameter
  character(len=256) :: exxdiv_treatment
  logical :: x_gamma_extrapolation
  real(dp) :: ecutvcut
  type :: functional_type
  type :: dft_type
  character(len=256) :: functional
  logical :: hybrid_ispresent
  type(hybrid_type) :: hybrid
  logical :: dftU_ispresent
  type(dftu_type) :: dftU
  logical :: vdW_ispresent
  type(vdw_type) :: vdW
  type :: d3vector_type
  type :: cell_type
  real(dp), dimension(3) :: a1
  real(dp), dimension(3) :: a2
  real(dp), dimension(3) :: a3
  type :: wyckoff_positions_type
  logical :: more_options_ispresent
  character(len=256) :: more_options
  integer :: ndim_atom
  type :: atomic_positions_type
  type :: atomic_structure_type
  logical :: alat_ispresent
  real(dp) :: alat
  logical :: bravais_index_ispresent
  integer :: bravais_index
  logical :: atomic_positions_ispresent
  type(atomic_positions_type) :: atomic_positions
  logical :: wyckoff_positions_ispresent
  type(wyckoff_positions_type) :: wyckoff_positions
  type(cell_type) :: cell
  type :: step_type
  integer :: n_step
  type(atomic_structure_type) :: atomic_structure
  type(total_energy_type) :: total_energy
  logical :: forces
  logical :: stress_ispresent
  logical :: stress
  logical :: FCP_force_ispresent
  real(dp) :: FCP_force
  logical :: FCP_tot_charge_ispresent
  real(dp) :: FCP_tot_charge
  type :: atomic_species_type
  integer :: ntyp
  type(species_type), allocatable, dimension(:) :: species
  integer :: ndim_species
  type :: output_type
  type(convergence_info_type) :: convergence_info
  type(algorithmic_info_type) :: algorithmic_info
  type(atomic_species_type) :: atomic_species
  type(symmetries_type) :: symmetries
  type(basis_set_type) :: basis_set
  type(dft_type) :: dft
  type(magnetization_type) :: magnetization
  type(band_structure_type) :: band_structure
  logical :: forces_ispresent
  logical :: electric_field_ispresent
  type(electric_field_type) :: electric_field
  type :: lowhigh_type
  type :: controlRestartMode_type
  type :: calculation_type
  type :: control_variables_type
  character(len=256) :: title
  character(len=256) :: calculation
  character(len=256) :: restart_mode
  character(len=256) :: prefix
  character(len=256) :: pseudo_dir
  character(len=256) :: outdir
  logical :: wf_collect
  character(len=256) :: disk_io
  integer :: max_seconds
  logical :: nstep_ispresent
  integer :: nstep
  real(dp) :: etot_conv_thr
  real(dp) :: forc_conv_thr
  real(dp) :: press_conv_thr
  character(len=256) :: verbosity
  integer :: print_every
  type :: input_type
  type(control_variables_type) :: control_variables
  type(bands_type) :: bands
  type(basis_type) :: basis
  type(electron_control_type) :: electron_control
  type(k_points_ibz_type) :: k_points_IBZ
  type(ion_control_type) :: ion_control
  type(cell_control_type) :: cell_control
  logical :: symmetry_flags_ispresent
  type(symmetry_flags_type) :: symmetry_flags
  logical :: boundary_conditions_ispresent
  type(boundary_conditions_type) :: boundary_conditions
  logical :: ekin_functional_ispresent
  type(ekin_functional_type) :: ekin_functional
  logical :: external_atomic_forces_ispresent
  type(matrix_type) :: external_atomic_forces
  logical :: free_positions_ispresent
  type(integermatrix_type) :: free_positions
  logical :: starting_atomic_velocities_ispresent
  type(matrix_type) :: starting_atomic_velocities
  logical :: atomic_constraints_ispresent
  type(atomic_constraints_type) :: atomic_constraints
  logical :: spin_constraints_ispresent
  type :: parallel_info_type
  integer :: nprocs
  integer :: nthreads
  integer :: ntasks
  integer :: nbgrp
  integer :: npool
  integer :: ndiag
  type :: created_type
  type(created_type) :: created
  type :: creator_type
  character(len=256) :: NAME
  character(len=256) :: VERSION
  type(creator_type) :: creator
  type :: xml_format_type
  type(xml_format_type) :: xml_format
  type :: general_info_type
  character(len=256) :: job
  character(len=256) :: job
contains
  procedure, pass :: alloc
  procedure, pass :: init
end type qes_types_module_type
