['alloc', 'init', 'dealloc']

subroutine alloc(this, n0)
  use memory_manager_module, only: memory_manager

  implicit none

  class(tsvdw_module_type), intent(inout) :: this
  integer, intent(in) :: n0

  integer :: istat

  allocate( UtsvdW(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'UtsvdW', UtsvdW(:), 1, istat)
  allocate( FtsvdW(:,:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'FtsvdW', FtsvdW(:,:), 1, istat)
  allocate( HtsvdW(:,:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'HtsvdW', HtsvdW(:,:), 1, istat)
  allocate( VefftsvdW(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'VefftsvdW', VefftsvdW(:), 1, istat)
  allocate( nstates(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'nstates', nstates(:), 1, istat)
  allocate( sdispls(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'sdispls', sdispls(:), 1, istat)
  allocate( rdispls(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'rdispls', rdispls(:), 1, istat)
  allocate( sendcount(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'sendcount', sendcount(:), 1, istat)
  allocate( recvcount(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'recvcount', recvcount(:), 1, istat)
  allocate( istatus(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'istatus', istatus(:), 1, istat)
  allocate( NsomegaA(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'NsomegaA', NsomegaA(:), 1, istat)
  allocate( NsomegaAr(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'NsomegaAr', NsomegaAr(:), 1, istat)
  allocate( npair(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'npair', npair(:), 1, istat)
  allocate( pair(:,:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'pair', pair(:,:), 1, istat)
  allocate( gomegar(:,:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'gomegar', gomegar(:,:), 1, istat)
  allocate( somegaA(:,:,:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'somegaA', somegaA(:,:,:), 1, istat)
  allocate( somegaAr(:,:,:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'somegaAr', somegaAr(:,:,:), 1, istat)
  allocate( gomegaAr(:,:,:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'gomegaAr', gomegaAr(:,:,:), 1, istat)
  allocate( predveffAdn(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'predveffAdn', predveffAdn(:), 1, istat)
  allocate( vfree(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'vfree', vfree(:), 1, istat)
  allocate( dpfree(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'dpfree', dpfree(:), 1, istat)
  allocate( R0free(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'R0free', R0free(:), 1, istat)
  allocate( C6AAfree(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'C6AAfree', C6AAfree(:), 1, istat)
  allocate( veff(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'veff', veff(:), 1, istat)
  allocate( dpeff(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'dpeff', dpeff(:), 1, istat)
  allocate( R0eff(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'R0eff', R0eff(:), 1, istat)
  allocate( C6AAeff(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'C6AAeff', C6AAeff(:), 1, istat)
  allocate( rhosad(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'rhosad', rhosad(:), 1, istat)
  allocate( rhotot(:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'rhotot', rhotot(:), 1, istat)
  allocate( dveffAdn(:,:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'dveffAdn', dveffAdn(:,:), 1, istat)
  allocate( spgrd(:,:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'spgrd', spgrd(:,:), 1, istat)
  allocate( sprho(:,:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'sprho', sprho(:,:), 1, istat)
  allocate( spdrho(:,:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'spdrho', spdrho(:,:), 1, istat)
  allocate( spdata(:,:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'spdata', spdata(:,:), 1, istat)
  allocate( LIA(:,:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'LIA', LIA(:,:), 1, istat)
  allocate( LIB(:,:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'LIB', LIB(:,:), 1, istat)
  allocate( dLIA(:,:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'dLIA', dLIA(:,:), 1, istat)
  allocate( dLIB(:,:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'dLIB', dLIB(:,:), 1, istat)
  allocate( atxyz(:,:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'atxyz', atxyz(:,:), 1, istat)
  allocate( C6ABfree(:,:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'C6ABfree', C6ABfree(:,:), 1, istat)
  allocate( C6ABeff(:,:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'C6ABeff', C6ABeff(:,:), 1, istat)
  allocate( dveffdR(:,:,:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'dveffdR', dveffdR(:,:,:), 1, istat)
  allocate( dveffdh(:,:,:), stat=istat )
  call memory_manager('tsvdw_module%alloc', 'dveffdh', dveffdh(:,:,:), 1, istat)
  this%is_alloc = .true.
  return
end subroutine alloc

subroutine init(this)
  implicit none

  class(tsvdw_module_type), intent(inout) :: this

  this%is_init = .true.
  return

end subroutine init

subroutine dealloc(this)
  use memory_manager_module, only: memory_manager

  implicit none

  class(tsvdw_module_type), intent(inout) :: this
  integer :: istat

  deallocate( UtsvdW, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'UtsvdW', UtsvdW(:), -1, istat)
  deallocate( FtsvdW, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'FtsvdW', FtsvdW(:,:), -1, istat)
  deallocate( HtsvdW, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'HtsvdW', HtsvdW(:,:), -1, istat)
  deallocate( VefftsvdW, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'VefftsvdW', VefftsvdW(:), -1, istat)
  deallocate( nstates, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'nstates', nstates(:), -1, istat)
  deallocate( sdispls, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'sdispls', sdispls(:), -1, istat)
  deallocate( rdispls, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'rdispls', rdispls(:), -1, istat)
  deallocate( sendcount, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'sendcount', sendcount(:), -1, istat)
  deallocate( recvcount, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'recvcount', recvcount(:), -1, istat)
  deallocate( istatus, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'istatus', istatus(:), -1, istat)
  deallocate( NsomegaA, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'NsomegaA', NsomegaA(:), -1, istat)
  deallocate( NsomegaAr, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'NsomegaAr', NsomegaAr(:), -1, istat)
  deallocate( npair, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'npair', npair(:), -1, istat)
  deallocate( pair, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'pair', pair(:,:), -1, istat)
  deallocate( gomegar, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'gomegar', gomegar(:,:), -1, istat)
  deallocate( somegaA, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'somegaA', somegaA(:,:,:), -1, istat)
  deallocate( somegaAr, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'somegaAr', somegaAr(:,:,:), -1, istat)
  deallocate( gomegaAr, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'gomegaAr', gomegaAr(:,:,:), -1, istat)
  deallocate( predveffAdn, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'predveffAdn', predveffAdn(:), -1, istat)
  deallocate( vfree, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'vfree', vfree(:), -1, istat)
  deallocate( dpfree, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'dpfree', dpfree(:), -1, istat)
  deallocate( R0free, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'R0free', R0free(:), -1, istat)
  deallocate( C6AAfree, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'C6AAfree', C6AAfree(:), -1, istat)
  deallocate( veff, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'veff', veff(:), -1, istat)
  deallocate( dpeff, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'dpeff', dpeff(:), -1, istat)
  deallocate( R0eff, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'R0eff', R0eff(:), -1, istat)
  deallocate( C6AAeff, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'C6AAeff', C6AAeff(:), -1, istat)
  deallocate( rhosad, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'rhosad', rhosad(:), -1, istat)
  deallocate( rhotot, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'rhotot', rhotot(:), -1, istat)
  deallocate( dveffAdn, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'dveffAdn', dveffAdn(:,:), -1, istat)
  deallocate( spgrd, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'spgrd', spgrd(:,:), -1, istat)
  deallocate( sprho, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'sprho', sprho(:,:), -1, istat)
  deallocate( spdrho, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'spdrho', spdrho(:,:), -1, istat)
  deallocate( spdata, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'spdata', spdata(:,:), -1, istat)
  deallocate( LIA, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'LIA', LIA(:,:), -1, istat)
  deallocate( LIB, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'LIB', LIB(:,:), -1, istat)
  deallocate( dLIA, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'dLIA', dLIA(:,:), -1, istat)
  deallocate( dLIB, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'dLIB', dLIB(:,:), -1, istat)
  deallocate( atxyz, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'atxyz', atxyz(:,:), -1, istat)
  deallocate( C6ABfree, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'C6ABfree', C6ABfree(:,:), -1, istat)
  deallocate( C6ABeff, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'C6ABeff', C6ABeff(:,:), -1, istat)
  deallocate( dveffdR, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'dveffdR', dveffdR(:,:,:), -1, istat)
  deallocate( dveffdh, stat=istat )
  call memory_manager('tsvdw_module%dealloc', 'dveffdh', dveffdh(:,:,:), -1, istat)
  this%is_alloc = .false.
  return
end subroutine dealloc

