['alloc', 'init', 'update', 'dealloc']

subroutine alloc(this, n0)
  use memory_manager_module, only: memory_manager

  implicit none

  class(input_parameters_type), intent(inout) :: this
  integer, intent(in) :: n0

  integer :: istat

  allocate( starting_magnetization(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'starting_magnetization', starting_magnetization(:), 1, istat)
  allocate( starting_ns_eigenvalue(:,:,:), stat=istat )
  call memory_manager('input_parameters%alloc', 'starting_ns_eigenvalue', starting_ns_eigenvalue(:,:,:), 1, istat)
  allocate( hubbard_u(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'hubbard_u', hubbard_u(:), 1, istat)
  allocate( hubbard_j0(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'hubbard_j0', hubbard_j0(:), 1, istat)
  allocate( hubbard_j(:,:), stat=istat )
  call memory_manager('input_parameters%alloc', 'hubbard_j', hubbard_j(:,:), 1, istat)
  allocate( hubbard_alpha(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'hubbard_alpha', hubbard_alpha(:), 1, istat)
  allocate( hubbard_beta(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'hubbard_beta', hubbard_beta(:), 1, istat)
  allocate( A_pen(:,:), stat=istat )
  call memory_manager('input_parameters%alloc', 'A_pen', A_pen(:,:), 1, istat)
  allocate( angle1(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'angle1', angle1(:), 1, istat)
  allocate( angle2(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'angle2', angle2(:), 1, istat)
  allocate( london_c6(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'london_c6', london_c6(:), 1, istat)
  allocate( london_rvdw(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'london_rvdw', london_rvdw(:), 1, istat)
  allocate( ion_radius(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'ion_radius', ion_radius(:), 1, istat)
  allocate( fnosep(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'fnosep', fnosep(:), 1, istat)
  allocate( nhgrp(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'nhgrp', nhgrp(:), 1, istat)
  allocate( fnhscl(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'fnhscl', fnhscl(:), 1, istat)
  allocate( tranp(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'tranp', tranp(:), 1, istat)
  allocate( amprp(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'amprp', amprp(:), 1, istat)
  allocate( cntr(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'cntr', cntr(:), 1, istat)
  allocate( step_rad(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'step_rad', step_rad(:), 1, istat)
  allocate( constrain_pot(:,:), stat=istat )
  call memory_manager('input_parameters%alloc', 'constrain_pot', constrain_pot(:,:), 1, istat)
  allocate( atom_label(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'atom_label', atom_label(:), 1, istat)
  allocate( atom_pfile(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'atom_pfile', atom_pfile(:), 1, istat)
  allocate( atom_mass(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'atom_mass', atom_mass(:), 1, istat)
  allocate( rd_pos(:,:), stat=istat )
  call memory_manager('input_parameters%alloc', 'rd_pos', rd_pos(:,:), 1, istat)
  allocate( sp_pos(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'sp_pos', sp_pos(:), 1, istat)
  allocate( if_pos(:,:), stat=istat )
  call memory_manager('input_parameters%alloc', 'if_pos', if_pos(:,:), 1, istat)
  allocate( na_inp(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'na_inp', na_inp(:), 1, istat)
  allocate( rd_vel(:,:), stat=istat )
  call memory_manager('input_parameters%alloc', 'rd_vel', rd_vel(:,:), 1, istat)
  allocate( sp_vel(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'sp_vel', sp_vel(:), 1, istat)
  allocate( rd_for(:,:), stat=istat )
  call memory_manager('input_parameters%alloc', 'rd_for', rd_for(:,:), 1, istat)
  allocate( xk(:,:), stat=istat )
  call memory_manager('input_parameters%alloc', 'xk', xk(:,:), 1, istat)
  allocate( wk(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'wk', wk(:), 1, istat)
  allocate( f_inp(:,:), stat=istat )
  call memory_manager('input_parameters%alloc', 'f_inp', f_inp(:,:), 1, istat)
  allocate( constr_type_inp(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'constr_type_inp', constr_type_inp(:), 1, istat)
  allocate( constr_inp(:,:), stat=istat )
  call memory_manager('input_parameters%alloc', 'constr_inp', constr_inp(:,:), 1, istat)
  allocate( constr_target_inp(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'constr_target_inp', constr_target_inp(:), 1, istat)
  allocate( constr_target_set(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'constr_target_set', constr_target_set(:), 1, istat)
  allocate( iprnks(:, :), stat=istat )
  call memory_manager('input_parameters%alloc', 'iprnks', iprnks(:, :), 1, istat)
  allocate( nprnks(:), stat=istat )
  call memory_manager('input_parameters%alloc', 'nprnks', nprnks(:), 1, istat)
  allocate( wannier_index(:,:), stat=istat )
  call memory_manager('input_parameters%alloc', 'wannier_index', wannier_index(:,:), 1, istat)
  allocate( wan_data(:,:), stat=istat )
  call memory_manager('input_parameters%alloc', 'wan_data', wan_data(:,:), 1, istat)
  this%is_alloc = .true.
  return
end subroutine alloc

subroutine init(this)
  implicit none

  class(input_parameters_type), intent(inout) :: this

  this%is_init = .true.
  return

end subroutine init

subroutine dealloc(this)
  use memory_manager_module, only: memory_manager

  implicit none

  class(input_parameters_type), intent(inout) :: this
  integer :: istat

  deallocate( starting_magnetization, stat=istat )
  call memory_manager('input_parameters%dealloc', 'starting_magnetization', starting_magnetization(:), -1, istat)
  deallocate( starting_ns_eigenvalue, stat=istat )
  call memory_manager('input_parameters%dealloc', 'starting_ns_eigenvalue', starting_ns_eigenvalue(:,:,:), -1, istat)
  deallocate( hubbard_u, stat=istat )
  call memory_manager('input_parameters%dealloc', 'hubbard_u', hubbard_u(:), -1, istat)
  deallocate( hubbard_j0, stat=istat )
  call memory_manager('input_parameters%dealloc', 'hubbard_j0', hubbard_j0(:), -1, istat)
  deallocate( hubbard_j, stat=istat )
  call memory_manager('input_parameters%dealloc', 'hubbard_j', hubbard_j(:,:), -1, istat)
  deallocate( hubbard_alpha, stat=istat )
  call memory_manager('input_parameters%dealloc', 'hubbard_alpha', hubbard_alpha(:), -1, istat)
  deallocate( hubbard_beta, stat=istat )
  call memory_manager('input_parameters%dealloc', 'hubbard_beta', hubbard_beta(:), -1, istat)
  deallocate( A_pen, stat=istat )
  call memory_manager('input_parameters%dealloc', 'A_pen', A_pen(:,:), -1, istat)
  deallocate( angle1, stat=istat )
  call memory_manager('input_parameters%dealloc', 'angle1', angle1(:), -1, istat)
  deallocate( angle2, stat=istat )
  call memory_manager('input_parameters%dealloc', 'angle2', angle2(:), -1, istat)
  deallocate( london_c6, stat=istat )
  call memory_manager('input_parameters%dealloc', 'london_c6', london_c6(:), -1, istat)
  deallocate( london_rvdw, stat=istat )
  call memory_manager('input_parameters%dealloc', 'london_rvdw', london_rvdw(:), -1, istat)
  deallocate( ion_radius, stat=istat )
  call memory_manager('input_parameters%dealloc', 'ion_radius', ion_radius(:), -1, istat)
  deallocate( fnosep, stat=istat )
  call memory_manager('input_parameters%dealloc', 'fnosep', fnosep(:), -1, istat)
  deallocate( nhgrp, stat=istat )
  call memory_manager('input_parameters%dealloc', 'nhgrp', nhgrp(:), -1, istat)
  deallocate( fnhscl, stat=istat )
  call memory_manager('input_parameters%dealloc', 'fnhscl', fnhscl(:), -1, istat)
  deallocate( tranp, stat=istat )
  call memory_manager('input_parameters%dealloc', 'tranp', tranp(:), -1, istat)
  deallocate( amprp, stat=istat )
  call memory_manager('input_parameters%dealloc', 'amprp', amprp(:), -1, istat)
  deallocate( cntr, stat=istat )
  call memory_manager('input_parameters%dealloc', 'cntr', cntr(:), -1, istat)
  deallocate( step_rad, stat=istat )
  call memory_manager('input_parameters%dealloc', 'step_rad', step_rad(:), -1, istat)
  deallocate( constrain_pot, stat=istat )
  call memory_manager('input_parameters%dealloc', 'constrain_pot', constrain_pot(:,:), -1, istat)
  deallocate( atom_label, stat=istat )
  call memory_manager('input_parameters%dealloc', 'atom_label', atom_label(:), -1, istat)
  deallocate( atom_pfile, stat=istat )
  call memory_manager('input_parameters%dealloc', 'atom_pfile', atom_pfile(:), -1, istat)
  deallocate( atom_mass, stat=istat )
  call memory_manager('input_parameters%dealloc', 'atom_mass', atom_mass(:), -1, istat)
  deallocate( rd_pos, stat=istat )
  call memory_manager('input_parameters%dealloc', 'rd_pos', rd_pos(:,:), -1, istat)
  deallocate( sp_pos, stat=istat )
  call memory_manager('input_parameters%dealloc', 'sp_pos', sp_pos(:), -1, istat)
  deallocate( if_pos, stat=istat )
  call memory_manager('input_parameters%dealloc', 'if_pos', if_pos(:,:), -1, istat)
  deallocate( na_inp, stat=istat )
  call memory_manager('input_parameters%dealloc', 'na_inp', na_inp(:), -1, istat)
  deallocate( rd_vel, stat=istat )
  call memory_manager('input_parameters%dealloc', 'rd_vel', rd_vel(:,:), -1, istat)
  deallocate( sp_vel, stat=istat )
  call memory_manager('input_parameters%dealloc', 'sp_vel', sp_vel(:), -1, istat)
  deallocate( rd_for, stat=istat )
  call memory_manager('input_parameters%dealloc', 'rd_for', rd_for(:,:), -1, istat)
  deallocate( xk, stat=istat )
  call memory_manager('input_parameters%dealloc', 'xk', xk(:,:), -1, istat)
  deallocate( wk, stat=istat )
  call memory_manager('input_parameters%dealloc', 'wk', wk(:), -1, istat)
  deallocate( f_inp, stat=istat )
  call memory_manager('input_parameters%dealloc', 'f_inp', f_inp(:,:), -1, istat)
  deallocate( constr_type_inp, stat=istat )
  call memory_manager('input_parameters%dealloc', 'constr_type_inp', constr_type_inp(:), -1, istat)
  deallocate( constr_inp, stat=istat )
  call memory_manager('input_parameters%dealloc', 'constr_inp', constr_inp(:,:), -1, istat)
  deallocate( constr_target_inp, stat=istat )
  call memory_manager('input_parameters%dealloc', 'constr_target_inp', constr_target_inp(:), -1, istat)
  deallocate( constr_target_set, stat=istat )
  call memory_manager('input_parameters%dealloc', 'constr_target_set', constr_target_set(:), -1, istat)
  deallocate( iprnks, stat=istat )
  call memory_manager('input_parameters%dealloc', 'iprnks', iprnks(:, :), -1, istat)
  deallocate( nprnks, stat=istat )
  call memory_manager('input_parameters%dealloc', 'nprnks', nprnks(:), -1, istat)
  deallocate( wannier_index, stat=istat )
  call memory_manager('input_parameters%dealloc', 'wannier_index', wannier_index(:,:), -1, istat)
  deallocate( wan_data, stat=istat )
  call memory_manager('input_parameters%dealloc', 'wan_data', wan_data(:,:), -1, istat)
  this%is_alloc = .false.
  return
end subroutine dealloc

